#include "yuv_shader_src.h"

//const char* YUV_SHADER_SRC = "uniform sampler2DRect Ytex;\r\n"
//                            "uniform sampler2DRect Utex,Vtex;\r\n"
//                            "void main(void)\r\n"
//                            "{\r\n"
//                            "float nx,ny,r,g,b,y,u,v;\r\n"
//                            "vec4 txl,ux,vx;\r\n"
//                            "nx=gl_TexCoord[0].x;\r\n"
//                            "ny=gl_TexCoord[0].y;\r\n"
//                            "y=texture2DRect(Ytex,vec2(nx,ny)).r;\r\n"
//                            "u=texture2DRect(Utex,vec2(nx/2.0,ny/2.0)).r;\r\n"
//                            "v=texture2DRect(Vtex,vec2(nx/2.0,ny/2.0)).r;\r\n"
//                            "y=1.1643*(y-0.0625);\r\n"
//                            "u=u - 0.5;\r\n"
//                            "v=v - 0.5;\r\n"
//                            "r=y+1.5958*v;\r\n"
//                            "g=y-0.39173*u-0.81290*v;\r\n"
//                            "b=y+2.017*u;\r\n"
//                            "gl_FragColor=vec4(r,g,b,1.0);\r\n"
//                            "}\r\n";
//const char* YUV_SHADER_SRC = "uniform sampler2D Ytex;\r\n"
//                             "uniform sampler2D Utex;\r\n"
//                             "uniform sampler2D Vtex;\r\n"
//                             "void main(void)\r\n"
//                             "{\r\n"
//                             "float nx,ny,r,g,b,y,u,v;\r\n"
//                             "vec4 txl,ux,vx;\r\n"
//                             "nx=gl_TexCoord[0].x;\r\n"
//                             "ny=gl_TexCoord[0].y;\r\n"
//                             "y=texture2D(Ytex,vec2(nx,ny)).r;\r\n"
//                             "u=texture2D(Utex,vec2(nx,ny)).r;\r\n"
//                             "v=texture2D(Vtex,vec2(nx,ny)).r;\r\n"
//                             "y=1.1643*(y-0.0625);\r\n"
//                             "u=u - 0.5;\r\n"
//                             "v=v - 0.5;\r\n"
//                             "r=y+1.5958*v;\r\n"
//                             "g=y-0.39173*u-0.81290*v;\r\n"
//                             "b=y+2.017*u;\r\n"
//                             "gl_FragColor=vec4(r,g,b,1.0);\r\n"
//                             "}\r\n";
