SET(CTEST_PROJECT_NAME "myv4l2")
SET(CTEST_NIGHTLY_START_TIME "01:00:00 UTC")

IF(NOT DEFINED CTEST_DROP_METHOD)
  SET(CTEST_DROP_METHOD "http")
ENDIF(NOT DEFINED CTEST_DROP_METHOD)

IF(CTEST_DROP_METHOD STREQUAL "http")
  SET(CTEST_DROP_SITE "192.168.1.14")
  SET(CTEST_DROP_LOCATION "/cdash/submit.php?project=pingsan")
  SET(CTEST_TRIGGER_SITE "")
ENDIF(CTEST_DROP_METHOD STREQUAL "http")
SET(CTEST_DROP_SITE_CDASH TRUE)

SET(CTEST_PROJECT_SUBPROJECTS my_v4l2)

